branches:
 only:
  - develop
  - master

git:
 depth: 1

language: objective-c

before_install:
 - wget "http://download.mono-project.com/archive/4.2.1/macos-10-x86/MonoFramework-MDK-4.2.1.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-4.2.1.macos10.xamarin.x86.pkg" -target /

before_script:
 - chmod +x .ci/nunit.sh
 - chmod +x src/.nuget/NuGet.exe

script:
 - ./src/.nuget/NuGet.exe restore ./src/Simplify.sln
 - xbuild /p:Platform="Any CPU" /p:Configuration=Release src/Simplify.sln
 - .ci/nunit.sh .ci/tests.nunit
